PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX oa:  <http://www.w3.org/ns/oa#>
PREFIX cnt: <http://www.w3.org/2011/content#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>

PREFIX : <http://spa.clinici.co#>


CONSTRUCT { ?s ?p ?o }
WHERE { GRAPH <http://spa.clinici.co/projects/1> {
 ?x oa:hasTarget <http://spa.clinici.co/documents/87168e2bacfa7fb217bfb32293f635> .
 ?x (:_|!:_)* ?s .
 ?s ?p ?o .
} .}