PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX oa:  <http://www.w3.org/ns/oa#>
PREFIX cnt: <http://www.w3.org/2011/content#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>

PREFIX spa: <http://spa.clinici.co/>

SELECT ?document ?body ?marginalia ?motivated ?highlight ?description {
GRAPH <http://spa.clinici.co/projects/1> {
      ?anno oa:hasTarget ?document .
      ?anno oa:hasBody ?body .
      ?anno spa:marginalia ?marginalia .
      ?anno oa:motivatedBy ?motivated .
      OPTIONAL {
               ?body  oa:hasSelector  ?selector .
               ?selector a oa:TextQuoteSelector .
               ?selector oa:exact ?highlight
               } .
      OPTIONAL {
               ?annot oa:motivatedBy oa:describing .
               ?body cnt:chars ?description
               }
    }
}
