PREFIX oa:  <http://www.w3.org/ns/oa#>
PREFIX spa: <http://spa.clinici.co/>

CONSTRUCT { ?s ?p ?o }
WHERE {
  GRAPH ?project {
    ?x oa:hasTarget ?target . FILTER ( regex(str(?target), ?documentRegex))
    ?x (spa:_|!spa:_)* ?s .
    ?s ?p ?o .
    } .
}
