PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX oa:  <http://www.w3.org/ns/oa#>
PREFIX cnt: <http://www.w3.org/2011/content#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX spa: <http://spa.clinici.co/>

INSERT DATA {
  GRAPH ?project {
    ?annotation a oa:Annotation ;
      oa:hasBody ?concept ;
      oa:motivatedBy oa:identifying ;
      oa:hasTarget ?target .

    ?target a oa:SpecificResource ;
      oa:hasSource ?document ;
      oa:hasSelector ?selector .

    ?selector a oa:TextQuoteSelector ;
      oa:exact ?quote ;
      oa:prefix  ?prefix ;
      oa:suffix ?suffix .
  }
}
