PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX oa:  <http://www.w3.org/ns/oa#>
PREFIX cnt: <http://www.w3.org/2011/content#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>

PREFIX spa: <http://spa.clinici.co/>

SELECT ?target ?concept ?conceptLabel ?highlight ?description {
  GRAPH ?project {
    ?concept a spa:Concept .
    ?concept rdfs:label ?conceptLabel ;
    OPTIONAL {
      ?anno oa:hasBody ?concept .
      ?anno oa:hasTarget ?target . FILTER ( regex(str(?target), ?documentRegex))
      OPTIONAL {
        ?target  oa:hasSelector ?selector .
        ?selector a oa:TextQuoteSelector .
        ?selector oa:exact ?highlight ;
      } .
      OPTIONAL {
        ?anno oa:hasBody ?descriptionBody .
        ?descriptionBody a cnt:ContentAsText .
        ?descriptionBody cnt:chars ?description ;
      }
    }
  }
}
