#!/usr/bin/env node

var program = require('commander');
var fs = require('fs');
var Q = require('q');
var path_module = require('path');
var Worker = require('./worker');

program
  .version(process.env.SPA_VERSION || "<I HAVE NO MASTER>")
  .option('-m, --module [module]', 'Module to use as handler for messages')
  .option('-s, --socket [socket]', 'ZeroMQ socket to listen on')
  .option('-n, --name [name]', 'Service name')
  .option('--timeout [timeout]', 'Maximum task duration before giving up', parseInt)
  .option('--heartbeat [heartbeat]', 'Sent a heartbeat every [heartbeat] milliseconds', parseInt)
  .option('--reconnect [reconnect]', 'Attempt to reconnect to disconnected broker after [reconnect] milliseconds', parseInt)
  .option('-p, --path [path]', 'Path to the module directory', path_module.join(__dirname, '../../topologies'))
  .parse(process.argv);


var path = path_module.join(program.path, program.module);
var handler = require(path);

function runServer(handler) {
  var p = program;
  var worker = new Worker(p.socket, p.name, p.timeout, p.heartbeat, p.reconnect);
  worker.start();

  worker.on('request', function(req, rep) {
    var result;
    try {
      result = handler(req);
      Q.when(result, function(data) {
        rep.reply(data);
      }, function(err) {
        rep.reply(err);
      });
    } catch (err) {
      console.error("Failed to process", err);
      result = JSON.stringify({cause: "Error: " + err});
      rep.reply(result);
    }
  });

}

runServer(handler);
